##programa test inicio
    inteiro a;
    a = 0;
    enquanto (a < 10) inicio
        a = a + 1;
        escreva(a);
    fim;
fim.##

##programa area_circulo inicio
  inteiro raio;
  booleano positivo;
  positivo = verdade;
  raio = 5;
  positivo = (raio > 1 | raio == 1);
  se (positivo == verdade) inicio
    real area;
    area = 3.1415 * raio * raio;
    escreva(area);
  fim;
fim.##




##programa primo inicio
    inteiro i, num;
    booleano eh_primo; 
    
    num = 5;
    i = 2;
    se (num <= 1)
        eh_primo = falso
    senao
        eh_primo = verdade;

    enquanto ( i < num & eh_primo == verdade) inicio
        se (num % i == 0)
            eh_primo = falso;
        i = i + 1;
    fim;
    escreva(eh_primo);
fim.##



##programa phi_se inicio
    inteiro a, b, c;
    leia(a);
    a = a * +2;
    se (a == 10) inicio
        b = a;
        c = 1;
    fim senao inicio
        b = 0;
        c = 0;
    fim;
    escreva(b);
    escreva(c);
fim.##


##programa teste_laco inicio
    inteiro i, soma;
    i = 1;
    leia(soma);
    enquanto (i <= 10) inicio
        soma = soma + i;
        i = i + 1;
    fim;
    escreva(soma);
fim.##

# Programa que determina se um número lido é primo ou não
programa primo inicio
    inteiro i, num;
    booleano eh_primo;
    
    real raio, area;
    raio = 5;
    area = 3.1415 * raio * raio;
    
    num = 7;
    i = 2;
    se (num <= 1)
        eh_primo = falso
    senao
        eh_primo = verdade;

    enquanto ( i < num & eh_primo == verdade) inicio
        se (num%i == 0)
            eh_primo = falso;
        i = i + +1;
    fim;
    escreva(eh_primo);
    escreva(area);
    
    i = 2;
    enquanto (i < 1000) inicio
        i = i^2;
        escreva(i);
    fim;
    
fim.