//Programa que determina se um número lido é primo ou não
programa primo inicio
    inteiro i, num;
    booleano eh_primo; 
    
    real raio, area;
    raio = 5;
    area = 3.1415 * raio * raio;
    
    num = 5 + 6;
    num = num - 7;
    i = 2;
    se (num <= 1)
        eh_primo = falso
    senao
        eh_primo = !falso;

    enquanto ( i < num & eh_primo == verdade) inicio
        se (num%i == 0)
            eh_primo = falso;
        i = i + +1;
    fim;
    escreva(eh_primo);
    escreva(area);
    
    i = 2;
    enquanto (i < 1000) inicio
        i = i^2;
        escreva(i);
    fim;
fim.
