/*programa teste_laco inicio
    inteiro i, soma;
    i = 1;
    soma = 0;
    enquanto (i <= 10) inicio
        soma = soma + i;
        i = i + 1;
    fim;
    escreva(soma);
fim.*/

programa phi_se inicio
    inteiro a, b;
    a = 5;
    a = a * 2;
    se (a == 10)
        b = a
    senao
        b = 0;
    escreva(b);
fim.

/*//Programa que determina se um número lido é primo ou não
programa primo inicio
    inteiro i, num;
    booleano eh_primo; 
    
    real raio, area;
    raio = 5;
    area = 3.1415 * raio * raio;
    
    num = 5 + 6;
    num = num - 7;
    i = 2;
    se (num <= 1)
        eh_primo = falso
    senao
        eh_primo = !falso;

    enquanto ( i < num & eh_primo == verdade) inicio
        se (num%i == 0)
            eh_primo = falso;
        i = i + +1;
    fim;
    escreva(eh_primo);
    escreva(area);
    
    i = 2;
    enquanto (i < 1000) inicio
        i = i^2;
        escreva(i);
    fim;
fim.
*/